[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "16.14.2" }

[context.deploy-preview]
  environment = { NODE_VERSION = "16.14.2" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 3000
  targetPort = 8080
  framework = "#custom"